package org.waterflane.villager_potential.core;

import java.util.Objects;
import java.util.Optional;

/**
 * Platform-independent identity for a generated villager trade.
 *
 * <p>An offer key describes the durable inputs and output of a trade. Platform
 * adapters are responsible for excluding runtime state such as demand, uses,
 * and temporary discounts when constructing one.</p>
 */
public sealed interface TradeKey permits TradeKey.Offer, TradeKey.Fallback {
    /**
     * A structured trade identity.
     */
    record Offer(Item costA, Optional<Item> costB, Item result) implements TradeKey {
        public Offer {
            Objects.requireNonNull(costA, "costA");
            Objects.requireNonNull(costB, "costB");
            Objects.requireNonNull(result, "result");
        }

        public Offer(Item costA, Item result) {
            this(costA, Optional.empty(), result);
        }
    }

    /**
     * Portable identity for one item stack participating in an offer.
     *
     * @param itemId namespaced platform item identifier, or a deterministic
     *               fallback identifier when the item is not registered
     * @param count stack count as generated by the trade
     * @param components canonical persistent component representation; empty
     *                   for an otherwise plain stack
     */
    record Item(String itemId, int count, String components) {
        public Item {
            if (itemId == null || itemId.isBlank()) {
                throw new IllegalArgumentException("Trade item ID cannot be blank");
            }
            if (count < 0) {
                throw new IllegalArgumentException("Trade item count cannot be negative");
            }
            Objects.requireNonNull(components, "components");
        }

        public Item(String itemId, int count) {
            this(itemId, count, "");
        }
    }

    /**
     * Last-resort identity for an offer whose normal shape cannot be read.
     */
    record Fallback(String representation) implements TradeKey {
        public Fallback {
            if (representation == null || representation.isBlank()) {
                throw new IllegalArgumentException("Fallback representation cannot be blank");
            }
        }
    }
}
