package org.waterflane.villager_potential.core;

import java.util.Objects;
import java.util.Optional;

/**
 * Platform-independent identity for a generated villager trade.
 *
 * <p>An offer key describes the durable inputs and output of a trade. Platform
 * adapters are responsible for excluding runtime state such as demand, uses,
 * and temporary discounts when constructing one.</p>
 *
 * <p>Adapters share one canonical fallback convention so persisted keys stay
 * portable: an item or component type that is not registered is identified as
 * {@code unregistered:<className>}, and a component value that cannot be
 * canonically encoded is represented as {@code fallback:<className>}. Keys
 * containing either marker are unstable and must never back durable memory.</p>
 */
public sealed interface TradeKey permits TradeKey.Offer, TradeKey.Fallback {
    /**
     * Reports whether the key is safe for durable memory, demand, and learned
     * palettes. Only structured offers whose items avoid every fallback marker
     * are stable; foreign or unreadable offers keep their {@link Fallback} key
     * so they can pass through hooks without being rejected.
     */
    static boolean isStable(TradeKey key) {
        Objects.requireNonNull(key, "key");
        if (!(key instanceof Offer offer)) {
            return false;
        }
        return hasStableItem(offer.costA())
                && offer.costB().map(TradeKey::hasStableItem).orElse(true)
                && hasStableItem(offer.result());
    }

    private static boolean hasStableItem(Item item) {
        return !item.itemId().startsWith("unregistered:")
                && TradeMetadata.isPortable(item.components());
    }

    /**
     * Reports whether two keys describe the same trade shape by item identity,
     * ignoring counts and component details. Persistent restoration uses this
     * to stop re-rolling candidates that can never match a learned trade.
     */
    static boolean sameShape(TradeKey generated, TradeKey learned) {
        Objects.requireNonNull(generated, "generated");
        Objects.requireNonNull(learned, "learned");
        if (!(generated instanceof Offer generatedOffer)
                || !(learned instanceof Offer learnedOffer)) {
            return generated.getClass().equals(learned.getClass());
        }
        return generatedOffer.costA().itemId().equals(learnedOffer.costA().itemId())
                && generatedOffer.result().itemId().equals(learnedOffer.result().itemId())
                && generatedOffer.costB().map(Item::itemId)
                .equals(learnedOffer.costB().map(Item::itemId));
    }

    /**
     * A structured trade identity.
     */
    record Offer(Item costA, Optional<Item> costB, Item result) implements TradeKey {
        public Offer {
            Objects.requireNonNull(costA, "costA");
            Objects.requireNonNull(costB, "costB");
            Objects.requireNonNull(result, "result");
        }

        public Offer(Item costA, Item result) {
            this(costA, Optional.empty(), result);
        }
    }

    /**
     * Portable identity for one item stack participating in an offer.
     *
     * @param itemId namespaced platform item identifier, or a deterministic
     *               fallback identifier when the item is not registered
     * @param count stack count as generated by the trade
     * @param components canonical portable metadata representation; empty for
     *                   an otherwise plain stack. The historical accessor name
     *                   is retained as part of the integration API.
     */
    record Item(String itemId, int count, String components) {
        public Item {
            if (itemId == null || itemId.isBlank()) {
                throw new IllegalArgumentException("Trade item ID cannot be blank");
            }
            if (count < 0) {
                throw new IllegalArgumentException("Trade item count cannot be negative");
            }
            Objects.requireNonNull(components, "components");
        }

        public Item(String itemId, int count) {
            this(itemId, count, "");
        }
    }

    /**
     * Last-resort identity for an offer whose normal shape cannot be read.
     */
    record Fallback(String representation) implements TradeKey {
        public Fallback {
            if (representation == null || representation.isBlank()) {
                throw new IllegalArgumentException("Fallback representation cannot be blank");
            }
        }
    }
}
